import turtle 
paper = turtle.Screen()
paper.bgcolor("green")
pen = turtle.Turtle()
pen.fillcolor("red")
pen.begin_fill()
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.end_fill()
pen.penup()
pen.forward(110)
pen.pendown()
pen.left(90)
pen.forward(180)
pen.right(90)
pen.forward(180)
pen.right(90)
pen.forward(180)
pen.right(90)
pen.forward(180)
          
turtle.done()
